app:
    resource: '@AppBundle/Controller/'
    type: annotation

home_show:
    path:      /home
    defaults:  { _controller: AppBundle:Default:home }

hello_the_world: 
    path:     /hello
    defaults:  { _controller: AppBundle:Hello:hello }

blog_stop_dev: 
    path:     /blog
    defaults:  { _controller: AppBundle:Blog:create }

admin_article_index:
    path:    /articles
    defaults: { _controller: AppBundle:Blog:show }
